### ISSUE TITLE
kirby or not kirby?

### ISSUE THREAD

**Issue by dirad** [gilbertnigg/kirby-mix#1]
During the install you get Kirby, but in the next step you delete it's public directory and then install ProcessWire instead...

What's going on here?

**Comment by gilbertnigg** [comment]
An optional workaround if you use the boilerplate for a different cms (e.g. ProcessWire) and keep the frontend dependencies. 
`composer create-project ... public` will have the public directory installed again and replaced with the new structure. 

This hint is now removed for confusing-reasons, see: https://github.com/gilbertnigg/kirby-mix/commit/4d07eda5f0de96a7d63be4ad1ceac8518e2f1908

**Comment by dirad** [comment]
ouch!
If you do prefer ProcessWire then it should probably stay there!
Mayb just mention that this is an optional thing. 🥇
